name: Java CI with Maven

on:
  pull_request:
    branches:
      - main
    paths:
      - 'api-treinamento-java/**'
      - 'docker-compose.yml'

jobs:
  test-java-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout c√≥digo
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Iniciar Banco de Dados PostgreSQL
        run: docker compose up -d db

      - name: Aguardar o Healthcheck do DB
        run: |
          echo "Aguardando o banco de dados ficar pronto..."
          timeout 60s bash -c 'until docker compose ps | grep "(healthy)"; do sleep 2; done'
        
      - name: Rodar os testes
        run: mvn -B test --file api-treinamento-java/pom.xml

      - name: Parar o Banco de Dados
        if: always()
        run: docker compose down